# Generated by Django 5.2.8 on 2026-01-09 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('feedback_app', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'feedback',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='FeedbackPet',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('feedback_pet', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'feedback_pet',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PessoaFisica',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('cpf', models.CharField(blank=True, db_column='CPF', max_length=14, null=True, unique=True)),
                ('data_nascimento', models.DateField(blank=True, db_column='DATA_NASCIMENTO', null=True)),
                ('genero', models.CharField(blank=True, db_column='GENERO', max_length=45, null=True)),
            ],
            options={
                'db_table': 'pessoa_fisica',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PessoaJuridica',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('cnpj', models.CharField(blank=True, db_column='CNPJ', max_length=14, null=True, unique=True)),
                ('nome_fantasia', models.CharField(blank=True, db_column='NOME_FANTASIA', max_length=45, null=True)),
                ('endereco', models.CharField(blank=True, db_column='ENDERECO', max_length=100, null=True)),
                ('data_criacao', models.DateField(blank=True, db_column='DATA_CRIACAO', null=True)),
            ],
            options={
                'db_table': 'pessoa_juridica',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nome', models.CharField(db_column='NOME', max_length=45)),
                ('data_nascimento', models.DateField(db_column='DATA_NASCIMENTO')),
                ('especie', models.CharField(db_column='ESPECIE', max_length=45)),
                ('raca', models.CharField(db_column='RACA', max_length=45)),
                ('sexo', models.CharField(db_column='SEXO', max_length=5)),
                ('pelagem', models.CharField(db_column='PELAGEM', max_length=45)),
                ('castrado', models.CharField(db_column='CASTRADO', max_length=3)),
                ('peso', models.CharField(blank=True, db_column='PESO', max_length=10, null=True)),
                ('descricao', models.TextField(blank=True, db_column='DESCRICAO', null=True)),
                ('personalidade', models.TextField(blank=True, db_column='PERSONALIDADE', null=True)),
                ('imagem', models.ImageField(blank=True, db_column='IMAGEM', null=True, upload_to='pets/')),
            ],
            options={
                'db_table': 'pet',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Prontuariopet',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('historico_veterinario', models.CharField(blank=True, db_column='HISTORICO_VETERINARIO', max_length=255, null=True)),
                ('motivo_consulta', models.TextField(blank=True, db_column='MOTIVO_CONSULTA', null=True)),
                ('avaliacao_geral', models.TextField(blank=True, db_column='AVALIACAO_GERAL', null=True)),
                ('procedimentos', models.TextField(blank=True, db_column='PROCEDIMENTOS', null=True)),
                ('diagnostico_conslusivo', models.TextField(blank=True, db_column='DIAGNOSTICO_CONSLUSIVO', null=True)),
                ('observacao', models.TextField(blank=True, db_column='OBSERVACAO', null=True)),
            ],
            options={
                'db_table': 'prontuariopet',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, db_column='NOME', max_length=100, null=True)),
                ('horario', models.TimeField(blank=True, db_column='HORARIO', null=True)),
                ('data_inicio', models.DateField(blank=True, db_column='DATA_INICIO', null=True)),
                ('data_fim', models.DateField(blank=True, db_column='DATA_FIM', null=True)),
                ('observacoes', models.TextField(blank=True, db_column='OBSERVACOES', null=True)),
                ('pet', models.ForeignKey(blank=True, db_column='ID_PET', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pet_app.pet')),
            ],
            options={
                'db_table': 'medicamento',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DiarioEmocional',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('humor', models.IntegerField(blank=True, db_column='HUMOR', null=True)),
                ('relato', models.TextField(blank=True, db_column='RELATO', null=True)),
                ('data_registro', models.DateTimeField(blank=True, db_column='DATA_REGISTRO', null=True)),
                ('pet', models.ForeignKey(db_column='ID_PET', on_delete=django.db.models.deletion.DO_NOTHING, to='pet_app.pet')),
            ],
            options={
                'db_table': 'diario_emocional',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nome_tutor', models.CharField(blank=True, db_column='nome_tutor', max_length=80, null=True)),
                ('cpf', models.CharField(blank=True, db_column='CPF', max_length=14, null=True, unique=True)),
                ('email', models.CharField(blank=True, db_column='EMAIL', max_length=80, null=True, unique=True)),
                ('endereco', models.CharField(blank=True, db_column='ENDERECO', max_length=100, null=True)),
                ('data_nascimento', models.DateField(blank=True, db_column='DATA_NASCIMENTO', null=True)),
                ('senha_tutor', models.CharField(db_column='senha_tutor', max_length=150)),
                ('imagem_perfil_tutor', models.ImageField(blank=True, db_column='imagem_perfil_tutor', null=True, upload_to='tutor/')),
                ('id_feedback_pet', models.ForeignKey(blank=True, db_column='ID_FEEDBACK_PET', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pet_app.feedbackpet')),
                ('id_feedback_sistema', models.ForeignKey(blank=True, db_column='ID_FEEDBACK_SISTEMA', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pet_app.feedback')),
            ],
            options={
                'db_table': 'tutor',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='pet',
            name='tutor',
            field=models.ForeignKey(db_column='ID_TUTOR', on_delete=django.db.models.deletion.DO_NOTHING, to='pet_app.tutor'),
        ),
        migrations.CreateModel(
            name='Vacina',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, db_column='NOME', max_length=100, null=True)),
                ('data_aplicacao', models.DateField(blank=True, db_column='DATA_APLICACAO', null=True)),
                ('proxima_dose', models.DateField(blank=True, db_column='PROXIMA_DOSE', null=True)),
                ('pet', models.ForeignKey(blank=True, db_column='ID_PET', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pet_app.pet')),
            ],
            options={
                'db_table': 'vacina',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Veterinario',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, db_column='NOME', max_length=45, null=True)),
                ('email', models.CharField(blank=True, db_column='EMAIL', max_length=45, null=True, unique=True)),
                ('crmv', models.IntegerField(blank=True, db_column='CRMV', null=True, unique=True)),
                ('uf_crmv', models.CharField(blank=True, db_column='UF_CRMV', max_length=5, null=True)),
                ('telefone', models.CharField(blank=True, db_column='TELEFONE', max_length=15, null=True)),
                ('senha_veterinario', models.CharField(blank=True, db_column='senha_veterinario', max_length=150, null=True)),
                ('imagem_perfil_veterinario', models.ImageField(blank=True, db_column='imagem_perfil_veterinario', null=True, upload_to='veterinario/')),
                ('pessoa_fisica', models.ForeignKey(blank=True, db_column='pessoa_fisica_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pet_app.pessoafisica')),
                ('pessoa_juridica', models.ForeignKey(blank=True, db_column='pessoa_juridica_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pet_app.pessoajuridica')),
            ],
            options={
                'db_table': 'veterinario',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='pet_app_notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensagem', models.TextField()),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('lida', models.BooleanField(default=True)),
                ('veterinario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to='pet_app.veterinario')),
            ],
            options={
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='ContatoVeterinario',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('tipo_contato', models.CharField(blank=True, db_column='TIPO_CONTATO', max_length=16, null=True)),
                ('ddd', models.CharField(blank=True, db_column='DDD', max_length=2, null=True)),
                ('numero', models.CharField(blank=True, db_column='NUMERO', max_length=9, null=True)),
                ('data_cadastro', models.DateTimeField(blank=True, db_column='DATA_CADASTRO', null=True)),
                ('veterinario', models.ForeignKey(db_column='ID_VETERINARIO', on_delete=django.db.models.deletion.DO_NOTHING, to='pet_app.veterinario')),
            ],
            options={
                'db_table': 'contato_veterinario',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('tipo_de_consulta', models.CharField(blank=True, db_column='TIPO_DE_CONSULTA', max_length=45, null=True)),
                ('retorno_agendado', models.DateField(blank=True, db_column='RETORNO_AGENDADO', null=True)),
                ('tratamento', models.CharField(blank=True, db_column='TRATAMENTO', max_length=100, null=True)),
                ('data_consulta', models.DateField(blank=True, db_column='DATA_CONSULTA', null=True)),
                ('horario_consulta', models.TimeField(blank=True, db_column='HORARIO_CONSULTA', null=True)),
                ('observacoes', models.CharField(blank=True, db_column='OBSERVACOES', max_length=255, null=True)),
                ('valor_consulta', models.DecimalField(blank=True, db_column='VALOR_CONSULTA', decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('status', models.CharField(blank=True, choices=[('Agendado', 'Agendado'), ('Confirmado', 'Confirmado'), ('Concluido', 'Concluído'), ('Cancelado', 'Cancelado')], db_column='STATUS', default='Agendado', max_length=20, null=True)),
                ('pet', models.ForeignKey(blank=True, db_column='ID_PET', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pet_app.pet')),
                ('veterinario', models.ForeignKey(blank=True, db_column='ID_VETERINARIO', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pet_app.veterinario')),
            ],
            options={
                'db_table': 'consulta',
                'managed': True,
            },
        ),
    ]
