# Generated by Django 5.2.8 on 2025-12-10 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('tipo_de_consulta', models.CharField(db_column='TIPO_DE_CONSULTA', max_length=45)),
                ('retorno_agendado', models.DateField(db_column='RETORNO_AGENDADO')),
                ('tratamento', models.CharField(db_column='TRATAMENTO', max_length=100)),
                ('data_consulta', models.DateField(db_column='DATA_CONSULTA')),
                ('horario_consulta', models.TimeField(db_column='HORARIO_CONSULTA')),
                ('observacoes', models.CharField(db_column='OBSERVACOES', max_length=45)),
            ],
            options={
                'db_table': 'consulta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ContatoTutor',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('tipo_contato', models.CharField(db_column='TIPO_CONTATO', max_length=16)),
                ('ddd', models.CharField(db_column='DDD', max_length=2)),
                ('numero', models.CharField(db_column='NUMERO', max_length=9)),
                ('data_cadastro', models.DateTimeField(blank=True, db_column='DATA_CADASTRO', null=True)),
            ],
            options={
                'db_table': 'contato_tutor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('feedback_app', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'feedback',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FeedbackPet',
            fields=[
                ('id', models.IntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('feedback_pet', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'feedback_pet',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PessoaFisica',
            fields=[
                ('id', models.IntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('cpf', models.IntegerField(db_column='CPF', unique=True)),
                ('data_nascimento', models.DateField(db_column='DATA_NASCIMENTO')),
                ('genero', models.CharField(db_column='GENERO', max_length=45)),
            ],
            options={
                'db_table': 'pessoa fisica',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PessoaJuridica',
            fields=[
                ('id', models.IntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('cnpj', models.IntegerField(db_column='CNPJ', unique=True)),
                ('nome_fantasia', models.CharField(db_column='NOME_FANTASIA', max_length=45)),
                ('endereco', models.CharField(db_column='ENDERECO', max_length=45)),
                ('data_criacao', models.DateField(db_column='DATA_CRIACAO')),
            ],
            options={
                'db_table': 'pessoa juridica',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nome', models.CharField(db_column='NOME', max_length=45)),
                ('data_nascimento', models.DateField(db_column='DATA_NASCIMENTO')),
                ('especie', models.CharField(db_column='ESPECIE', max_length=45)),
                ('raca', models.CharField(max_length=45)),
                ('sexo', models.CharField(db_column='SEXO', max_length=5)),
                ('pelagem', models.CharField(db_column='PELAGEM', max_length=45)),
                ('castrado', models.CharField(db_column='CASTRADO', max_length=3)),
            ],
            options={
                'db_table': 'pet',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProntuarioPet',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('historico_veterinario', models.CharField(db_column='HISTORICO_VETERINARIO', max_length=150, unique=True)),
                ('motivo_consulta', models.TextField(db_column='MOTIVO_CONSULTA')),
                ('avaliacao_geral', models.TextField(db_column='AVALIACAO_GERAL')),
                ('procedimentos', models.TextField(db_column='PROCEDIMENTOS')),
                ('diagnostico_conslusivo', models.TextField(db_column='DIAGNOSTICO_CONSLUSIVO')),
                ('observacao', models.TextField(db_column='OBSERVACAO')),
            ],
            options={
                'db_table': 'prontuario_pet',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nome_tutor', models.CharField(blank=True, max_length=80, null=True)),
                ('cpf', models.CharField(blank=True, db_column='CPF', max_length=14, null=True, unique=True)),
                ('email', models.CharField(blank=True, max_length=80, null=True)),
                ('endereco', models.CharField(db_column='ENDERECO', max_length=100)),
                ('data_nascimento', models.DateField(db_column='DATA_NASCIMENTO')),
                ('senha_tutor', models.CharField(max_length=150)),
                ('imagem_perfil_tutor', models.ImageField(upload_to='tutor')),
            ],
            options={
                'db_table': 'tutor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Veterinario',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nome', models.CharField(db_column='NOME', max_length=45)),
                ('email', models.CharField(db_column='EMAIL', max_length=45)),
                ('crmv', models.IntegerField(db_column='CRMV', unique=True)),
                ('uf_crmv', models.CharField(db_column='UF_CRMV', max_length=5)),
                ('telefone', models.IntegerField(db_column='TELEFONE')),
                ('senha_veterinario', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'veterinario',
                'managed': False,
            },
        ),
    ]
