# Generated by Django 5.2.8 on 2025-12-09 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pet_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tutor',
            options={},
        ),
        migrations.AlterModelOptions(
            name='veterinario',
            options={},
        ),
        migrations.AlterModelTable(
            name='pessoafisica',
            table='pessoa_fisica',
        ),
        migrations.AlterModelTable(
            name='pessoajuridica',
            table='veterinario',
        ),
    ]
