# Generated by Django 5.2.8 on 2026-01-15 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='imagem_perfil_tutor',
            field=models.ImageField(upload_to='tutor'),
        ),
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensagem', models.TextField()),
                ('tipo', models.CharField(default='sistema', max_length=20)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('lida', models.BooleanField(default=False)),
                ('tutor', models.ForeignKey(blank=True, db_column='tutor_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes_tutor', to='pet_app.tutor')),
                ('veterinario', models.ForeignKey(blank=True, db_column='veterinario_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to='pet_app.veterinario')),
            ],
            options={
                'db_table': 'pet_app_notificacao',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.DeleteModel(
            name='pet_app_notificacao',
        ),
    ]
