# Generated by Django 5.2.8 on 2026-01-15 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_app', '0002_alter_tutor_imagem_perfil_tutor_notificacao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CONTEUDO', models.TextField(db_column='CONTEUDO', default='')),
                ('DATA_ENVIO', models.DateTimeField(auto_now_add=True, db_column='DATA_ENVIO')),
                ('ENVIADO_POR', models.CharField(db_column='ENVIADO_POR', default='TUTOR', max_length=15)),
                ('LIDA', models.BooleanField(db_column='LIDA', default=False)),
                ('TUTOR', models.ForeignKey(db_column='ID_TUTOR', on_delete=django.db.models.deletion.CASCADE, to='pet_app.tutor')),
                ('VETERINARIO', models.ForeignKey(db_column='ID_VETERINARIO', on_delete=django.db.models.deletion.CASCADE, to='pet_app.veterinario')),
            ],
            options={
                'db_table': 'mensagem',
                'ordering': ['DATA_ENVIO'],
            },
        ),
    ]
