# Generated by Django 6.0 on 2025-12-15 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pet_app', '0002_alter_tutor_options_alter_veterinario_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContatoTutor',
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
        migrations.DeleteModel(
            name='FeedbackPet',
        ),
        migrations.AlterModelOptions(
            name='tutor',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='veterinario',
            options={'managed': False},
        ),
        migrations.AlterModelTable(
            name='pessoajuridica',
            table='pessoa_juridica',
        ),
    ]
