# Generated by Django 5.2.8 on 2025-12-15 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pet_app', '0003_delete_contatotutor_delete_feedback_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProntuarioPet',
        ),
    ]
