# Generated by Django 5.2.8 on 2026-01-15 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_app', '0003_add_mensagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='prontuariopet',
            name='pet',
            field=models.ForeignKey(blank=True, db_column='ID_PET', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pet_app.pet'),
        ),
    ]
