# Generated by Django 5.2.8 on 2026-01-15 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_app', '0004_fix_prontuariopet_id_pet'),
    ]

    operations = [
        migrations.AddField(
            model_name='prontuariopet',
            name='veterinario',
            field=models.ForeignKey(blank=True, db_column='ID_VETERINARIO', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pet_app.veterinario'),
        ),
    ]
