# Generated by Django 6.0 on 2025-12-29 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_app', '0004_delete_prontuariopet'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContatoTutor',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('tipo_contato', models.CharField(db_column='TIPO_CONTATO', max_length=16)),
                ('ddd', models.CharField(db_column='DDD', max_length=2)),
                ('numero', models.CharField(db_column='NUMERO', max_length=9)),
                ('data_cadastro', models.DateTimeField(db_column='DATA_CADASTRO')),
            ],
            options={
                'db_table': 'contato_tutor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('feedback_app', models.TextField(blank=True, db_column='FEEDBACK_APP', null=True)),
            ],
            options={
                'db_table': 'feedback',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FeedbackPet',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('feedback_pet', models.TextField(blank=True, db_column='FEEDBACK_PET', null=True)),
            ],
            options={
                'db_table': 'feedback_pet',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProntuarioPet',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('historico_veterinario', models.CharField(db_column='HISTORICO_VETERINARIO', max_length=255)),
                ('motivo_consulta', models.TextField(db_column='MOTIVO_CONSULTA')),
                ('avaliacao_geral', models.TextField(db_column='AVALIACAO_GERAL')),
                ('procedimentos', models.TextField(db_column='PROCEDIMENTOS')),
                ('diagnostico_conslusivo', models.TextField(db_column='DIAGNOSTICO_CONSLUSIVO')),
                ('observacao', models.TextField(db_column='OBSERVACAO')),
            ],
            options={
                'db_table': 'prontuariopet',
                'managed': False,
            },
        ),
    ]
