# Generated by Django 5.2.8 on 2026-01-15 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_app', '0005_fix_prontuariopet_id_veterinario'),
    ]

    operations = [
        migrations.AddField(
            model_name='prontuariopet',
            name='motivo_consulta',
            field=models.TextField(blank=True, db_column='MOTIVO_CONSULTA', null=True),
        ),
        migrations.AddField(
            model_name='prontuariopet',
            name='avaliacao_geral',
            field=models.TextField(blank=True, db_column='AVALIACAO_GERAL', null=True),
        ),
        migrations.AddField(
            model_name='prontuariopet',
            name='procedimentos',
            field=models.TextField(blank=True, db_column='PROCEDIMENTOS', null=True),
        ),
        migrations.AddField(
            model_name='prontuariopet',
            name='diagnostico_conslusivo',
            field=models.TextField(blank=True, db_column='DIAGNOSTICO_CONSLUSIVO', null=True),
        ),
        migrations.AddField(
            model_name='prontuariopet',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, blank=True, db_column='DATA_CRIACAO', null=True),
        ),
    ]
