# Generated by Django 5.2.8 on 2026-01-05 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_app', '0005_contatotutor_feedback_feedbackpet_prontuariopet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacina',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nome', models.CharField(db_column='NOME', max_length=100)),
                ('data_aplicacao', models.DateField(db_column='DATA_APLICACAO')),
                ('proxima_dose', models.DateField(blank=True, db_column='PROXIMA_DOSE', null=True)),
                ('peso', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('personalidade', models.CharField(blank=True, max_length=255, null=True)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='pets/')),
            ],
            options={
                'db_table': 'vacina',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='consulta',
            options={'managed': True},
        ),
    ]
