# Generated by Django 5.2.8 on 2026-01-09 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_app', '0005_contatotutor_feedback_feedbackpet_prontuariopet'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiarioEmocional',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('humor', models.IntegerField(blank=True, db_column='HUMOR', null=True)),
                ('relato', models.TextField(blank=True, db_column='RELATO', null=True)),
                ('data_registro', models.DateTimeField(blank=True, db_column='DATA_REGISTRO', null=True)),
            ],
            options={
                'db_table': 'diario_emocional',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, db_column='NOME', max_length=100, null=True)),
                ('horario', models.TimeField(blank=True, db_column='HORARIO', null=True)),
                ('data_inicio', models.DateField(blank=True, db_column='DATA_INICIO', null=True)),
                ('data_fim', models.DateField(blank=True, db_column='DATA_FIM', null=True)),
                ('observacoes', models.TextField(blank=True, db_column='OBSERVACOES', null=True)),
            ],
            options={
                'db_table': 'medicamento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vacina',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, db_column='NOME', max_length=100, null=True)),
                ('data_aplicacao', models.DateField(blank=True, db_column='DATA_APLICACAO', null=True)),
                ('proxima_dose', models.DateField(blank=True, db_column='PROXIMA_DOSE', null=True)),
            ],
            options={
                'db_table': 'vacina',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CodigoRecuperacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('codigo', models.CharField(max_length=5)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo', models.TextField()),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
                ('enviado_por_tutor', models.BooleanField(default=True)),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pet_app.tutor')),
                ('veterinario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pet_app.veterinario')),
            ],
            options={
                'db_table': 'mensagens',
                'ordering': ['data_envio'],
            },
        ),
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensagem', models.TextField()),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('lida', models.BooleanField(default=False)),
                ('veterinario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to='pet_app.veterinario')),
            ],
            options={
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.DeleteModel(
            name='ContatoTutor',
        ),
    ]
