# Generated by Django 5.2.8 on 2026-01-15 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_app', '0006_add_remaining_prontuariopet_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='prontuariopet',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, blank=True, db_column='DATA_CRIACAO', null=True),
        ),
    ]
