# Generated by Django 5.2.8 on 2026-01-07 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pet_app', '0006_diarioemocional_medicamento_vacina_codigorecuperacao_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tutor',
            options={'managed': True},
        ),
    ]
