# Generated by Django 5.2.8 on 2026-01-07 20:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_app', '0007_alter_tutor_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mensagem',
            options={'ordering': ['DATA_ENVIO']},
        ),
        migrations.RemoveField(
            model_name='mensagem',
            name='conteudo',
        ),
        migrations.RemoveField(
            model_name='mensagem',
            name='data_envio',
        ),
        migrations.RemoveField(
            model_name='mensagem',
            name='enviado_por_tutor',
        ),
        migrations.AddField(
            model_name='mensagem',
            name='ENVIADO_POR',
            field=models.CharField(db_column='ENVIADO_POR', default='TUTOR', max_length=15),
        ),
        migrations.AddField(
            model_name='mensagem',
            name='LIDA',
            field=models.BooleanField(db_column='LIDA', default=False),
        ),
        migrations.AddField(
            model_name='tutor',
            name='id_feedback_pet',
            field=models.ForeignKey(blank=True, db_column='ID_FEEDBACK_PET', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pet_app.feedbackpet'),
        ),
        migrations.AddField(
            model_name='tutor',
            name='id_feedback_sistema',
            field=models.ForeignKey(blank=True, db_column='ID_FEEDBACK_SISTEMA', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pet_app.feedback'),
        ),
        migrations.AddField(
            model_name='tutor',
            name='status_conta',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='mensagem',
            name='tutor',
            field=models.ForeignKey(db_column='ID_TUTOR', on_delete=django.db.models.deletion.CASCADE, to='pet_app.tutor'),
        ),
        migrations.AlterField(
            model_name='mensagem',
            name='veterinario',
            field=models.ForeignKey(db_column='ID_VETERINARIO', on_delete=django.db.models.deletion.CASCADE, to='pet_app.veterinario'),
        ),
        migrations.AlterModelTable(
            name='mensagem',
            table='mensagem',
        ),
        migrations.AddField(
            model_name='mensagem',
            name='CONTEUDO',
            field=models.TextField(db_column='CONTEUDO', default=''),
        ),
        migrations.AddField(
            model_name='mensagem',
            name='DATA_ENVIO',
            field=models.DateTimeField(auto_now_add=True, db_column='DATA_ENVIO', default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
