# Generated by Django 5.2.8 on 2026-02-01 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_app', '0007_add_data_criacao_prontuariopet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='status',
            field=models.CharField(blank=True, choices=[('Pendente', 'Pendente'), ('Agendado', 'Agendado'), ('Confirmado', 'Confirmado'), ('Concluido', 'Concluído'), ('Cancelado', 'Cancelado')], db_column='STATUS', default='Pendente', max_length=20, null=True),
        ),
    ]
