# Generated by Django 5.2.8 on 2026-01-12 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pet_app', '0008_alter_mensagem_options_remove_mensagem_conteudo_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            ALTER TABLE prontuariopet ADD COLUMN ID_PET INT NULL;
            ALTER TABLE prontuariopet ADD COLUMN ID_VETERINARIO INT NULL;
            ALTER TABLE prontuariopet ADD COLUMN DATA_CRIACAO DATETIME NULL DEFAULT CURRENT_TIMESTAMP;
            """,
            reverse_sql="""
            ALTER TABLE prontuariopet DROP COLUMN ID_PET;
            ALTER TABLE prontuariopet DROP COLUMN ID_VETERINARIO;
            ALTER TABLE prontuariopet DROP COLUMN DATA_CRIACAO;
            """
        ),
    ]
