# Generated by Django 5.2.8 on 2026-01-12 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pet_app', '0008_alter_mensagem_options_remove_mensagem_conteudo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prontuariopet',
            name='pet',
            field=models.ForeignKey(blank=True, db_column='ID_PET', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pet_app.pet'),
        ),
        migrations.AddField(
            model_name='prontuariopet',
            name='veterinario',
            field=models.ForeignKey(blank=True, db_column='ID_VETERINARIO', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pet_app.veterinario'),
        ),
        migrations.AddField(
            model_name='prontuariopet',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, blank=True, db_column='DATA_CRIACAO', null=True),
        ),
    ]
