# Generated by Django 5.2.8 on 2026-01-12 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pet_app', '0009_add_prontuario_columns'),
        ('pet_app', '0009_add_prontuario_fks'),
    ]

    operations = [
    ]
