# Generated by Django 5.2.8 on 2026-01-12 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_app', '0010_merge_20260112_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacao',
            name='tipo',
            field=models.CharField(default='sistema', max_length=20),
        ),
        migrations.AddField(
            model_name='notificacao',
            name='tutor',
            field=models.ForeignKey(blank=True, db_column='tutor_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes_tutor', to='pet_app.tutor'),
        ),
        migrations.AlterField(
            model_name='notificacao',
            name='veterinario',
            field=models.ForeignKey(blank=True, db_column='ID_VETERINARIO', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to='pet_app.veterinario'),
        ),
        migrations.AlterModelTable(
            name='notificacao',
            table='pet_app_notificacao',
        ),
    ]
