# Generated by Django 6.0 on 2025-12-15 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('tipo_de_consulta', models.CharField(db_column='TIPO_DE_CONSULTA', max_length=45)),
                ('retorno_agendado', models.DateField(blank=True, db_column='RETORNO_AGENDADO', null=True)),
                ('tratamento', models.CharField(blank=True, db_column='TRATAMENTO', max_length=100, null=True)),
                ('data_consulta', models.DateField(db_column='DATA_CONSULTA')),
                ('horario_consulta', models.TimeField(db_column='HORARIO_CONSULTA')),
                ('observacoes', models.TextField(blank=True, db_column='OBSERVACOES', null=True)),
                ('valor_consulta', models.DecimalField(db_column='VALOR_CONSULTA', decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('Agendado', 'Agendado'), ('Confirmado', 'Confirmado'), ('Concluido', 'Concluído'), ('Cancelado', 'Cancelado')], db_column='STATUS', default='Agendado', max_length=20)),
            ],
            options={
                'db_table': 'consulta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ContatoVeterinario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_contato', models.CharField(max_length=16)),
                ('ddd', models.CharField(max_length=2)),
                ('numero', models.CharField(max_length=9)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'contato_veterinario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PessoaFisica',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('cpf', models.CharField(db_column='CPF', max_length=14, unique=True)),
                ('data_nascimento', models.DateField(db_column='DATA_NASCIMENTO')),
                ('genero', models.CharField(db_column='GENERO', max_length=45)),
            ],
            options={
                'db_table': 'pessoa_fisica',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PessoaJuridica',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('cnpj', models.CharField(db_column='CNPJ', max_length=14, unique=True)),
                ('nome_fantasia', models.CharField(db_column='NOME_FANTASIA', max_length=45)),
                ('endereco', models.CharField(db_column='ENDERECO', max_length=100)),
                ('data_criacao', models.DateField(db_column='DATA_CRIACAO')),
            ],
            options={
                'db_table': 'pessoa_juridica',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nome', models.CharField(db_column='NOME', max_length=45)),
                ('data_nascimento', models.DateField(db_column='DATA_NASCIMENTO')),
                ('especie', models.CharField(db_column='ESPECIE', max_length=45)),
                ('raca', models.CharField(max_length=45)),
                ('sexo', models.CharField(db_column='SEXO', max_length=5)),
                ('pelagem', models.CharField(db_column='PELAGEM', max_length=45)),
                ('castrado', models.CharField(db_column='CASTRADO', max_length=3)),
            ],
            options={
                'db_table': 'pet',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProntuarioPet',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('historico_veterinario', models.CharField(db_column='HISTORICO_VETERINARIO', max_length=150, unique=True)),
                ('motivo_consulta', models.TextField(db_column='MOTIVO_CONSULTA')),
                ('avaliacao_geral', models.TextField(db_column='AVALIACAO_GERAL')),
                ('procedimentos', models.TextField(db_column='PROCEDIMENTOS')),
                ('diagnostico_conslusivo', models.TextField(db_column='DIAGNOSTICO_CONSLUSIVO')),
                ('observacao', models.TextField(db_column='OBSERVACAO')),
            ],
            options={
                'db_table': 'prontuario_pet',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nome_tutor', models.CharField(blank=True, max_length=80, null=True)),
                ('cpf', models.CharField(blank=True, db_column='CPF', max_length=14, null=True, unique=True)),
                ('email', models.CharField(blank=True, db_column='EMAIL', max_length=80, null=True, unique=True)),
                ('endereco', models.CharField(db_column='ENDERECO', max_length=100)),
                ('data_nascimento', models.DateField(db_column='DATA_NASCIMENTO')),
                ('senha_tutor', models.CharField(max_length=150)),
                ('imagem_perfil_tutor', models.ImageField(blank=True, null=True, upload_to='tutor')),
            ],
            options={
                'db_table': 'tutor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Veterinario',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nome', models.CharField(db_column='NOME', max_length=45)),
                ('email', models.CharField(db_column='EMAIL', max_length=45, unique=True)),
                ('crmv', models.IntegerField(db_column='CRMV', unique=True)),
                ('uf_crmv', models.CharField(db_column='UF_CRMV', max_length=5)),
                ('telefone', models.CharField(db_column='TELEFONE', max_length=15)),
                ('imagem_perfil_veterinario', models.ImageField(blank=True, null=True, upload_to='veterinario')),
                ('senha_veterinario', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'veterinario',
                'managed': False,
            },
        ),
    ]
