# Generated by Django 6.0 on 2026-01-06 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vet_dash', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacina',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nome', models.CharField(db_column='NOME', max_length=100)),
                ('data_aplicacao', models.DateField(db_column='DATA_APLICACAO')),
                ('proxima_dose', models.DateField(blank=True, db_column='PROXIMA_DOSE', null=True)),
            ],
            options={
                'db_table': 'vacina',
                'managed': False,
            },
        ),
        migrations.AlterModelTable(
            name='prontuariopet',
            table='prontuariopet',
        ),
    ]
