# Generated by Django 5.2.8 on 2025-12-09 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutor_dash', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consulta',
            options={},
        ),
        migrations.AlterModelOptions(
            name='contatotutor',
            options={},
        ),
        migrations.AlterModelOptions(
            name='contatoveterinario',
            options={},
        ),
        migrations.AlterModelOptions(
            name='feedback',
            options={},
        ),
        migrations.AlterModelOptions(
            name='feedbackpet',
            options={},
        ),
        migrations.AlterModelOptions(
            name='pessoafisica',
            options={},
        ),
        migrations.AlterModelOptions(
            name='pessoajuridica',
            options={},
        ),
        migrations.AlterModelOptions(
            name='pet',
            options={},
        ),
        migrations.AlterModelOptions(
            name='prontuariopet',
            options={},
        ),
        migrations.AlterModelOptions(
            name='tutor',
            options={},
        ),
        migrations.AlterModelOptions(
            name='veterinario',
            options={},
        ),
    ]
