# Generated by Django 5.2.8 on 2025-12-09 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutor_dash', '0002_alter_consulta_options_alter_contatotutor_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consulta',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='contatotutor',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='contatoveterinario',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='feedback',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='feedbackpet',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='pessoafisica',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='pessoajuridica',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='pet',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='prontuariopet',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='tutor',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='veterinario',
            options={'managed': False},
        ),
    ]
