# Generated by Django 5.2.8 on 2025-12-09 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutor_dash', '0003_alter_consulta_options_alter_contatotutor_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='veterinario',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='pessoafisica',
            table='pessoa_fisica',
        ),
        migrations.AlterModelTable(
            name='pessoajuridica',
            table='pessoa_juridica',
        ),
    ]
