# Generated by Django 5.2.8 on 2025-12-09 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutor_dash', '0004_alter_veterinario_options_alter_pessoafisica_table_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='veterinario',
            options={'managed': False},
        ),
        migrations.AlterModelTable(
            name='pessoafisica',
            table='pessoa fisica',
        ),
        migrations.AlterModelTable(
            name='pessoajuridica',
            table='pessoa juridica',
        ),
    ]
