# Generated by Django 6.0 on 2025-12-15 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutor_dash', '0005_alter_veterinario_options_alter_pessoafisica_table_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='prontuariopet',
            table='prontuariopet',
        ),
    ]
