# Generated by Django 6.0 on 2025-12-15 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutor_dash', '0006_alter_prontuariopet_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContatoVeterinario',
        ),
        migrations.DeleteModel(
            name='PessoaFisica',
        ),
        migrations.DeleteModel(
            name='PessoaJuridica',
        ),
    ]
