# Generated by Django 6.0 on 2025-12-30 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor_dash', '0007_delete_contatoveterinario_delete_pessoafisica_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContatoVeterinario',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('tipo_contato', models.CharField(db_column='TIPO_CONTATO', max_length=16)),
                ('ddd', models.CharField(db_column='DDD', max_length=2)),
                ('numero', models.CharField(db_column='NUMERO', max_length=9)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, db_column='DATA_CADASTRO')),
            ],
            options={
                'db_table': 'contato_veterinario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DiarioEmocional',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('humor', models.IntegerField(db_column='HUMOR')),
                ('relato', models.TextField(db_column='RELATO')),
                ('data_registro', models.DateTimeField(auto_now_add=True, db_column='DATA_REGISTRO')),
            ],
            options={
                'db_table': 'diario_emocional',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PessoaFisica',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('cpf', models.CharField(db_column='CPF', max_length=14, unique=True)),
                ('data_nascimento', models.DateField(db_column='DATA_NASCIMENTO')),
                ('genero', models.CharField(db_column='GENERO', max_length=45)),
            ],
            options={
                'db_table': 'pessoa_fisica',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PessoaJuridica',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('cnpj', models.CharField(db_column='CNPJ', max_length=14, unique=True)),
                ('nome_fantasia', models.CharField(db_column='NOME_FANTASIA', max_length=45)),
                ('endereco', models.CharField(db_column='ENDERECO', max_length=100)),
                ('data_criacao', models.DateField(db_column='DATA_CRIACAO')),
            ],
            options={
                'db_table': 'pessoa_juridica',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vacina',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nome', models.CharField(db_column='NOME', max_length=100)),
                ('data_aplicacao', models.DateField(db_column='DATA_APLICACAO')),
                ('proxima_dose', models.DateField(blank=True, db_column='PROXIMA_DOSE', null=True)),
            ],
            options={
                'db_table': 'vacina',
                'managed': False,
            },
        ),
    ]
