# Generated by Django 6.0 on 2025-12-30 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor_dash', '0008_contatoveterinario_diarioemocional_pessoafisica_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('horario', models.TimeField()),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('pet', models.ForeignKey(db_column='ID_PET', on_delete=django.db.models.deletion.CASCADE, to='tutor_dash.pet')),
            ],
            options={
                'db_table': 'medicamento',
                'managed': True,
            },
        ),
    ]
