# Generated by Django 6.0 on 2026-01-04 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutor_dash', '0009_medicamento'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Medicamento',
        ),
    ]
