-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_pet
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_pet
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_pet` DEFAULT CHARACTER SET utf8 ;
USE `db_pet` ;

-- -----------------------------------------------------
-- Table `db_pet`.`FEEDBACK`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_pet`.`FEEDBACK` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `FEEDBACK_APP` VARCHAR(45) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_pet`.`FEEDBACK_PET`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_pet`.`FEEDBACK_PET` (
  `ID` INT NOT NULL,
  `FEEDBACK_PET` VARCHAR(45) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_pet`.`TUTOR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_pet`.`TUTOR` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NOME_TUTOR` VARCHAR(45) NOT NULL,
  `CPF` INT(11) NOT NULL,
  `EMAIL` VARCHAR(45) NOT NULL,
  `ENDEREÇO` VARCHAR(100) NOT NULL,
  `DATA DE NASCIMENTO` DATE NULL,
  `ID_FEEDBACK_SISTEMA` INT NOT NULL,
  `ID_FEEDBACK_PET` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_TUTOR_FEEDBACK1_idx` (`ID_FEEDBACK_SISTEMA` ASC) VISIBLE,
  INDEX `fk_TUTOR_FEEDBACK_PET1_idx` (`ID_FEEDBACK_PET` ASC) VISIBLE,
  UNIQUE INDEX `CPF_UNIQUE` (`CPF` ASC) VISIBLE,
  CONSTRAINT `fk_TUTOR_FEEDBACK1`
    FOREIGN KEY (`ID_FEEDBACK_SISTEMA`)
    REFERENCES `db_pet`.`FEEDBACK` (`ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_TUTOR_FEEDBACK_PET1`
    FOREIGN KEY (`ID_FEEDBACK_PET`)
    REFERENCES `db_pet`.`FEEDBACK_PET` (`ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_pet`.`PRONTUARIO_PET`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_pet`.`PRONTUARIO_PET` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `HISTORICO_VETERINARIO` VARCHAR(150) NOT NULL,
  `MOTIVO_CONSULTA` TEXT(150) NOT NULL,
  `AVALIACAO_GERAL` TEXT(150) NOT NULL,
  `PROCEDIMENTOS` TEXT(150) NOT NULL,
  `DIAGNOSTICO_CONSLUSIVO` TEXT(150) NOT NULL,
  `OBSERVACAO` TEXT(150) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `HISTORICO_VETERINARIO_UNIQUE` (`HISTORICO_VETERINARIO` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_pet`.`PET`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_pet`.`PET` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NOME` VARCHAR(45) NOT NULL,
  `DATA_NASCIMENTO` DATE NOT NULL,
  `ESPECIE` VARCHAR(45) NOT NULL,
  `RAÇA` VARCHAR(45) NOT NULL,
  `SEXO` ENUM('Macho', 'Femea') NOT NULL,
  `PELAGEM` VARCHAR(45) NOT NULL,
  `CASTRADO` ENUM('Sim', 'Não') NOT NULL,
  `ID_TUTOR` INT NOT NULL,
  `ID_CONSULTA` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_PET_TUTOR_idx` (`ID_TUTOR` ASC) VISIBLE,
  INDEX `fk_PET_REGISTRO_PET1_idx` (`ID_CONSULTA` ASC) VISIBLE,
  CONSTRAINT `fk_PET_TUTOR`
    FOREIGN KEY (`ID_TUTOR`)
    REFERENCES `db_pet`.`TUTOR` (`ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_PET_REGISTRO_PET1`
    FOREIGN KEY (`ID_CONSULTA`)
    REFERENCES `db_pet`.`PRONTUARIO_PET` (`ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_pet`.`PESSOA JURIDICA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_pet`.`PESSOA JURIDICA` (
  `ID` INT NOT NULL,
  `CNPJ` INT(14) NOT NULL,
  `NOME_FANTASIA` VARCHAR(45) NOT NULL,
  `ENDERECO` VARCHAR(45) NOT NULL,
  `DATA_CRIACAO` DATE NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `CNPJ_UNIQUE` (`CNPJ` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_pet`.`PESSOA FISICA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_pet`.`PESSOA FISICA` (
  `ID` INT NOT NULL,
  `CPF` INT(11) NOT NULL,
  `DATA_NASCIMENTO` DATE NOT NULL,
  `GENERO` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `CPF_UNIQUE` (`CPF` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_pet`.`VETERINARIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_pet`.`VETERINARIO` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NOME` VARCHAR(45) NOT NULL,
  `EMAIL` VARCHAR(45) NOT NULL,
  `CRMV` INT(6) NOT NULL,
  `UF_CRMV` VARCHAR(5) NOT NULL,
  `TELEFONE` INT(11) NOT NULL,
  `PESSOA JURIDICA_idPESSOA JURIDICA` INT NOT NULL,
  `PESSOA FISICA_idPESSOA FISICA` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_VETERINARIO_PESSOA JURIDICA1_idx` (`PESSOA JURIDICA_idPESSOA JURIDICA` ASC) VISIBLE,
  INDEX `fk_VETERINARIO_PESSOA FISICA1_idx` (`PESSOA FISICA_idPESSOA FISICA` ASC) VISIBLE,
  UNIQUE INDEX `CRMV_UNIQUE` (`CRMV` ASC) VISIBLE,
  CONSTRAINT `fk_VETERINARIO_PESSOA JURIDICA1`
    FOREIGN KEY (`PESSOA JURIDICA_idPESSOA JURIDICA`)
    REFERENCES `db_pet`.`PESSOA JURIDICA` (`ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_VETERINARIO_PESSOA FISICA1`
    FOREIGN KEY (`PESSOA FISICA_idPESSOA FISICA`)
    REFERENCES `db_pet`.`PESSOA FISICA` (`ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_pet`.`CONSULTA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_pet`.`CONSULTA` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `TIPO_DE_CONSULTA` VARCHAR(45) NOT NULL,
  `RETORNO_AGENDADO` DATE NOT NULL,
  `TRATAMENTO` VARCHAR(100) NOT NULL,
  `DATA_CONSULTA` DATE NOT NULL,
  `HORARIO_CONSULTA` TIME NOT NULL,
  `OBSERVACOES` VARCHAR(45) NOT NULL,
  `ID_PET` INT NOT NULL,
  `ID_VETERINARIO` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_CONSULTA_PET1_idx` (`ID_PET` ASC) VISIBLE,
  INDEX `fk_CONSULTA_VETERINARIO1_idx` (`ID_VETERINARIO` ASC) VISIBLE,
  CONSTRAINT `fk_CONSULTA_PET1`
    FOREIGN KEY (`ID_PET`)
    REFERENCES `db_pet`.`PET` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CONSULTA_VETERINARIO1`
    FOREIGN KEY (`ID_VETERINARIO`)
    REFERENCES `db_pet`.`VETERINARIO` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;