use mydb;

ALTER TABLE tutor 
ADD COLUMN DATA_NASCIMENTO DATE NULL;

ALTER TABLE tutor 
ADD COLUMN ID_FEEDBACK_SISTEMA INT NULL,
ADD COLUMN ID_FEEDBACK_PET INT NULL,
ADD CONSTRAINT fk_tutor_feedback_sistema 
    FOREIGN KEY (ID_FEEDBACK_SISTEMA) REFERENCES feedback(ID),
ADD CONSTRAINT fk_tutor_feedback_pet 
    FOREIGN KEY (ID_FEEDBACK_PET) REFERENCES feedback_pet(ID);
    
ALTER TABLE tutor 
ADD COLUMN senha_tutor VARCHAR(150) NOT NULL DEFAULT '';

ALTER TABLE tutor 
ADD COLUMN imagem_perfil_tutor VARCHAR(100) NULL DEFAULT NULL;